/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseCardError: typeof import('./components/base/BaseCardError.vue')['default']
    BaseEditableInput: typeof import('./components/base/BaseEditableInput.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseNavbar: typeof import('./components/base/BaseNavbar.vue')['default']
    BaseSwitchToggle: typeof import('./components/base/BaseSwitchToggle.vue')['default']
    BaseToast: typeof import('./components/base/BaseToast.vue')['default']
    BaseToggleButton: typeof import('./components/base/BaseToggleButton.vue')['default']
    DomainForm: typeof import('./components/post/domain/DomainForm.vue')['default']
    InputRow: typeof import('./components/post/domain/InputRow/InputRow.vue')['default']
    LoginCard: typeof import('./components/LoginCard/LoginCard.vue')['default']
    MovieCard: typeof import('./components/movie/MovieCard.vue')['default']
    MovieCardLoading: typeof import('./components/movie/MovieCardLoading.vue')['default']
    MovieSearchBar: typeof import('./components/movie/MovieSearchBar.vue')['default']
    PostApp: typeof import('./components/post/PostApp.vue')['default']
    PostCard: typeof import('./components/post/PostCard.vue')['default']
    PostDetailsApp: typeof import('./components/post/PostDetailsApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
