name: release-build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy webhook
        run: |
          curl -X POST -d '{}' ${{secrets.WEBHOOK_DEPLOY}}
