name: release-build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Deploy webhook
        run: |
          curl -X POST -d '{}' ${{secrets.WEBHOOK_DEPLOY}}
